# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: New-agent
  vmImage: New-agent

steps:
- task: CmdLine@2
  name: terraform init
  inputs:
    script: 'terraform init'
- task: CmdLine@2
  name: terraform apply
  inputs:
    script: 'terraform apply -auto-approve'
