trigger:
- main

pool:
  name: New-agent
  vmImage: New-agent  # Make sure Terraform is installed on your self-hosted agent

steps:
- checkout: self

- script: |
    echo "Terraform Init"
    export GITHUB_TOKEN=$(GITHUB_TOKEN)
    terraform init
  displayName: 'Terraform Init'

- script: |
    echo "Terraform Plan"
    export GITHUB_TOKEN=$(GITHUB_TOKEN)
    terraform plan
  displayName: 'Terraform Plan'

- script: |
    echo "Testing GitHub token..."
    export GITHUB_TOKEN=$(GITHUB_TOKEN)
    curl -s -o response.json -w "%{http_code}" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user
    echo "GitHub API response:"
    cat response.json
  displayName: "🔍 Test GitHub Token"

- script: |
    echo "Terraform Apply"
    export GITHUB_TOKEN=$(GITHUB_TOKEN)
    terraform apply -auto-approve
  displayName: 'Terraform Apply'

