trigger:
- main

pool:
  name: New-agent
  vmImage: New-agent  # Only if you've defined a self-hosted agent named this

steps:
- checkout: self

- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    command: 'init'

- script: |
    echo "Running Terraform Plan"
    export GITHUB_TOKEN=$GITHUB_TOKEN
    terraform plan
  displayName: 'Terraform Plan'

- script: |
    echo "Running Terraform Apply"
    export GITHUB_TOKEN=$GITHUB_TOKEN
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
